---
- hosts: okeanos
  sudo: true
  gather_facts: false

  tasks:

    - name: remove maellak user
      user: name=maellak state=absent remove=yes

    - name: remove default user
      user: name=user state=absent remove=yes
