---
#
# Run with `-e ssh_port=22`. Replace 22 with custom port.
#
- hosts: okeanos
  sudo: true
  gather_facts: false

  handlers:
    - name: restart sshd
      service: name=ssh state=restarted

  tasks:

    - name: remove maellak user
      user: name=maellak state=absent remove=yes

    - name: remove default user
      user: name=user state=absent remove=yes

    - name: change vagrant password
      user: >
        name=vagrant
        password=$1$PVMfG7Xb$MCRDqywrAdQJw3QV4OOXa/

    - name: disable ssh permitrootlogin
      lineinfile:
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644
      notify: restart sshd
      tags:
        - ssh

    - name: change ssh port
      lineinfile:
        regexp: "Port "
        line: "Port {{ ssh_port }}"
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644
      notify: restart sshd
      tags:
        - ssh
