---
- hosts: all
  sudo: true

  tasks:

    - name: Copy postinstall scripts
      copy:
        src: "postinstall/{{ item }}"
        dest: /root/
        owner: root
        group: root
        mode: 755
      with_items:
        - mongo_fix.sh
        - provision.sh
