---
- hosts: all
  sudo: true

  vars:
    - mongo_path: /edx/var/mongo/mongodb

  tasks:

    - name: mongodb | stop service
      service: name=mongod state=stopped

    - name: mongodb | remove mongo.lock
      file: name="{{ mongo_path}}/mongod.lock" state=absent

    - name: mongodb | remove mongo admin dir
      file: name="{{ mongo_path}}/admin" state=absent

    - name: mongodb | remove mongo local dir
      file: name="{{ mongo_path}}/local" state=absent

    - name: mongo | start mongodb
      service: name=mongod state=started

    - name: mongodb | fix permissions
      file:
        name: "{{ mongo_path}}/"
        owner: mongodb
        group: mongodb
        recurse: yes
