---
galaxy_info:
  author: Nick Janetakis
  description: Install and configure fail2ban.
  company:
  license: license MIT
  min_ansible_version: 1.5

  platforms:
  - name: Ubuntu
    versions:
    - all

  categories:
  - networking
  - system
  - web

dependencies: []