---
- name: remove maellak user
  user: name=maellak state=absent remove=yes
  tags:
    - user

- name: remove default user
  user: name=user state=absent remove=yes
  tags:
    - user

- name: Remove unneeded sources
  command: rm {{ sources_path  }}{{ item }}
  with_items:
    - google-chrome.list
    - google-chrome.list.save
    - x2go-stable-precise.list
    - x2go-stable-precise.list.save
    - grnet-synnefo-precise.list

- name: remove packages
  apt: name={{ item }} state=absent purge=yes update_cache=yes
  with_items:
    - libx11*
    - libqt*
    - libice6
    - firefox
    - firefox-globalmenu
    - firefox-locale-en
    - google-chrome-stable
    - thunderbird
    - cups
    - avahi-daemon
    - alsa-base
    - pulseaudio
    - x11-common
    - xserver-xorg-core
    - postfix
    - libsane
    - acpid
    - speech-dispatcher
  tags:
    - packages

- name: disable services
  service: name={{ item }} enabled=false state=stopped
  with_items:
  tags:
    - services

- name: Add packages
  apt: name={{ item }} state=present
  with_items:
    - fail2ban
    - syslog-summary
    - mysql-server
  tags:
    - packages

- name: Enable and start services
  service: name={{ item }} state=started enabled=true
  with_items:
    - mysql
    - mongod
  tags:
    - services

- name: Copy postinstall scripts
  copy:
    src: "{{ item }}"
    dest: /root/
    owner: root
    group: root
    mode: 755
  with_items:
    - mongo_fix.sh
    - provision.sh

- name: Install unattended-upgrades
  action: apt pkg=unattended-upgrades state=present

- name: Adjust APT update intervals
  copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic

- name: Make sure unattended-upgrades only installs from $ubuntu_release-security
  action: lineinfile dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent

- name: Elasticsearch listen to localhost
  lineinfile:
    regexp: "network.host"
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "network.host: localhost"
    owner: root
    group: root
    mode: 0644
  tags:
    - elastic
  notify:
    - restart elasticsearch

- name: Bind mongo to localhost
  lineinfile:
    dest: /etc/mongod.conf
    line: "bind_ip = 127.0.0.1"
    owner: root
    group: root
    mode: 0644
  tags:
    - mongo
  notify:
    - restart mongo
